### ISSUE TITLE
401 error on Twitch API call

### ISSUE THREAD

**Issue by mjmatta** [tmarenko/twitch_chat_antiban#11]
Hi. This extension very recently stopped working for me on Chrome, causing a blank gray chat.

![7d0b8b4790bd3aae7ea84135dee20cd2](https://user-images.githubusercontent.com/90805572/231908576-733cfa3c-632a-4987-9d89-887a873ff718.png)

From what I can find I'm getting a 401 Unauthorized on the call to api.twitch.tv/helix/users.

![cc2887740927c44939d195a19ba813be](https://user-images.githubusercontent.com/90805572/231908953-5762ccd5-8339-4ef8-b859-991680699c0a.png)

I've tried logging out and in and clearing cookies -- I'm wondering if this is a problem with my browser or if there's some expired token or something on your end? Thanks.

**Comment by tmarenko** [comment]
Yeah, it is expired token. I'm currently setting up external API so next time I wouldn't need to update the token manually in the extension.

**Comment by mjmatta** [comment]
Cool, thanks for the very quick reply.

**Comment by tmarenko** [comment]
Fixed in https://github.com/tmarenko/twitch_chat_antiban/commit/5a7c245353cea9bd072b8d3b5ba0fb6a743297ed
Extension is updated both in Chrome and Firefox stores.
