### ISSUE TITLE
Extension no longer works.

### ISSUE THREAD

**Issue by GardoTL** [tmarenko/twitch_chat_antiban#13]
![image](https://user-images.githubusercontent.com/90606692/235205541-94c96155-3a45-4ee4-ac58-b7c1f96f3e4a.png)

**Comment by tmarenko** [comment]
No response ¯\_(ツ)_/¯

**Comment by icynstant** [comment]
Please open it, I have same problem. I'll give all info in next comment

**Comment by icynstant** [comment]
My chat looks like exactly like on GardoTL's screenshot. I tested it with turned off all my add ons except anti-ban.

Browser: Firefox Nightly (it's like alpha)
Add on version: 3.2 (I installed it from firefox site)

Console screenshot:
![Screenshot_1](https://github.com/tmarenko/twitch_chat_antiban/assets/127024748/ef4ca95a-93b3-459b-95a1-c8d86f2b4ba7)

Thank you for your fast response!

**Comment by tmarenko** [comment]
Please check if the extension is asking you for permissions (I think you need to click on extension icon):
![image](https://github.com/tmarenko/twitch_chat_antiban/assets/31345208/d405ad5b-cffc-4dea-a3a4-e41b0d7a4dd0)

I still haven't updated the code to [background scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#communicating_with_background_scripts) so Firefox might require to grant the network access manually

**Comment by icynstant** [comment]
> Please check if the extension is asking you for permissions (I think you need to click on extension icon): ![image](https://user-images.githubusercontent.com/31345208/280815948-d405ad5b-cffc-4dea-a3a4-e41b0d7a4dd0.png)
> 
> I still haven't updated the code to [background scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#communicating_with_background_scripts) so Firefox might require to grant the network access manually

It's not asking me for permissions, I gave it everything I could in all settings, it has "Access to your data for sites in the twitch.tv domain".

I can't click on it, in Firefox I can only click on those add-ons that have their own built-in settings.

**Comment by tmarenko** [comment]
Oh right, I forgot to update 7TV permission for new host:
https://github.com/tmarenko/twitch_chat_antiban/blob/07ca781476f36454259b01640dae469ae07bea60/src/manifest.firefox.json#L12
should be `7tv.io` now

**Comment by tmarenko** [comment]
Fixed in https://github.com/tmarenko/twitch_chat_antiban/commit/074ea960c04e4594358b352db70e7ec02ebdc80b
New 3.2.1 version is already up at Firefox store

> Is there anything I can do manually to fix this?

Just update the extension =)

> Other problems appear on the twitch website when this add-on is enabled (It's also laggy) (may be this info will be useful for you)

Sure, please create new issue and describe your problems. I'll close this one

**Comment by icynstant** [comment]
> Исправлено в [ 074ea96. ](https://github.com/tmarenko/twitch_chat_antiban/commit/074ea960c04e4594358b352db70e7ec02ebdc80b) Новая версия 3.2.1 уже доступна в магазине Firefox.
> 
> > Могу ли я что-нибудь сделать вручную, чтобы это исправить?
> 
> Просто обновите расширение =)
> 
> > Другие проблемы появляются на сайте twitch при включении этого дополнения (оно тоже тормозит) (возможно эта информация будет вам полезна)
> 
> Конечно, пожалуйста, создайте новую задачу и опишите свои проблемы. Я закрою это

It works. Also it's not laggy anymore and other problems is gone. Ty so much for such a quick help
