### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by kurtdh** [tmarenko/twitch_chat_antiban#14]
Can you enable this addon to work on sites like twitchtheater.tv? I'm not sure how difficult that would be, but it would be enormously helpful. Thank you.

**Comment by tmarenko** [comment]
I've enabled iframe matching in https://github.com/tmarenko/twitch_chat_antiban/commit/5bc7624da411e2bc22174cb2cbbc2d275cef7bcb
Please update to latest 2.9 release

**Comment by kurtdh** [comment]
Wow, that was amazingly fast. I'll test it out on twitchtheater.tv later when I get a chance. Thank you!
