### ISSUE TITLE
The addon doesn't work on twitchtheater.tv

### ISSUE THREAD

**Issue by kurtdh** [tmarenko/twitch_chat_antiban#15]
![image](https://github.com/tmarenko/twitch_chat_antiban/assets/26121469/2ccb1564-1df8-48a2-b0dc-6086a5006feb)

See screenshot. It says it's connected to #embed but it doesn't show the chat. I have twitch.tv open in a second window and it works just fine on that site, but not on twitchtheater.tv

**Comment by tmarenko** [comment]
Right, totally missed that iframe has different URL. Here is a fix: https://github.com/tmarenko/twitch_chat_antiban/commit/c4001c1e389c243c65fe5989b365e97df6b5afa5
Please update to latest 2.10 version and check

**Comment by kurtdh** [comment]
Ok I'll check, but there's no easy way to test it, so it might be a while before I can report back the results.

**Comment by kurtdh** [comment]
Confirmed working for me. Thanks for the fix!
