### ISSUE TITLE
7tv emotes don't work

### ISSUE THREAD

**Issue by zett121** [tmarenko/twitch_chat_antiban#8]
7tv emotes don't work and it makes the chat unreadable.. a lot of channels use it nowadays

**Comment by tmarenko** [comment]
Duplicate: https://github.com/tmarenko/twitch_chat_antiban/issues/7

Though I wonder if it's possible to make own IRC client for chat instead of using 3rd party tools.
Will leave this issue open for now.

**Comment by sangakuu** [comment]
Yo I was kinda searching for a solution and I think I found one. You could try using jChat instead of Nightdev/KapChat.

**Comment by tmarenko** [comment]
Unfortunately, jChat provides very (IMO) limited options to customize its appearance. 
The fonts and their sizes, in particular, do not look that great. Additionally, it is impossible to inject custom CSS styles into an iframe due to the cross-domain policy. 
However, jChat has shown me that it is possible to create a custom chat reader through IRC, so I am now considering that option.

**Comment by tmarenko** [comment]
I made an update in https://github.com/tmarenko/twitch_chat_antiban/tree/irc-chat
Now the chat is completely reworked and support 7TV/BTTV/FFZ

For now you can install it either by cloning source code or just drag&drop [this archive](https://github.com/tmarenko/twitch_chat_antiban/files/11063323/src-irc-chat.zip) into Chrome extension tab.

If you could test and report any bugs that would be grateful 
@robmonte @sangakuu @zett121

**Comment by robmonte** [comment]
So far no issues for me, works great and loads all emotes

**Comment by tmarenko** [comment]
@zett121 this one is be fine, forgot to remove Firefox manifest from archive. Extension should work anyway even with this error

**Comment by zett121** [comment]
can confirm works good even with the error. great job

**Comment by tmarenko** [comment]
Merged https://github.com/tmarenko/twitch_chat_antiban/pull/10 and released
